---
run:
  modules-download-mode: readonly
linters:
  enable-all: true
  disable:
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - ireturn
    - testpackage
    - tenv
    - gci
    - godot
    - wrapcheck
    - reassign
    - godox
    - dupl
    - varnamelen

linters-settings:
  depguard:
    rules:
      main:
        list-mode: strict
        allow:
          - $gostd
          - github.com/weastur
          - github.com/spf13/cobra
          - github.com/spf13/viper
          - github.com/gofiber/fiber/v2
          - github.com/vrecan/death/v3
          - github.com/VictoriaMetrics/metrics
          - github.com/gofiber/contrib/swagger
          - github.com/rs/zerolog
          - github.com/gofiber/contrib/fiberzerolog
          - github.com/getsentry/sentry-go
          - github.com/gofiber/contrib/fibersentry
          - github.com/hashicorp/raft
          - github.com/hashicorp/raft-boltdb/v2
        deny:
          - pkg: "math/rand$"
            desc: use math/rand/v2
  forbidigo:
    forbid:
      - ^print(ln)?$
    exclude-godoc-examples: true
    analyze-types: true
  paralleltest:
    ignore-missing: true
    ignore-missing-subtests: true
  errcheck:
    disable-default-exclusions: true
    exclude-functions:
      - (*github.com/spf13/viper.Viper).BindPFlag
      - (*github.com/spf13/cobra.Command).MarkFlagFilename
  wsl:
    allow-cuddle-with-calls:
      - Done
      - Add
