---
run:
  modules-download-mode: readonly
linters:
  enable-all: true
  disable:
    - exhaustruct
    - exportloopref
    - gochecknoglobals
    - gochecknoinits
    - ireturn
    - testpackage

linters-settings:
  depguard:
    rules:
      main:
        list-mode: strict
        allow:
          - $gostd
          - github.com/weastur
          - github.com/spf13/cobra
          - github.com/spf13/viper
          - github.com/gofiber/fiber/v2
        deny:
          - pkg: "math/rand$"
            desc: use math/rand/v2
  varnamelen:
    ignore-decls:
      - t testing.T
      - e error
      - i int
      - T any
      - w http.ResponseWriter
      - r *http.Request
  forbidigo:
    forbid:
      - ^print(ln)?$
    exclude-godoc-examples: true
    analyze-types: true
  paralleltest:
    ignore-missing: true
    ignore-missing-subtests: true
  errcheck:
    disable-default-exclusions: true
    exclude-functions:
      - (*github.com/spf13/viper.Viper).BindPFlag
      - (*github.com/spf13/cobra.Command).MarkFlagFilename
