version: "3"

vars:
  BUILD_FLAGS: '-tags netgo,static_build,osusergo,feature -ldflags "-extldflags "-static" -X github.com/weastur/maf/internal/utils.version=v0.0.0-dev" -gcflags=all="-N -l"'
  SWAGGO_VERSION: "v1.16.4"
  REPLACER_VERSION: "v1.0.0"
  COBRA_CLI_VERSION: "latest"
  GOLANGCI_LINT_VERSION: "v2.0.2"

tasks:
  build:
    desc: Build the binary
    deps: [swagger]
    env:
      CGO_ENABLED: 0
    cmds:
      - go build {{.BUILD_FLAGS}} -o maf{{exeExt}}
    sources:
      - ./**/*.go
    generates:
      - maf{{exeExt}}

  test:
    desc: Run tests
    env:
      CGO_ENABLED: 0
    cmds:
      - go test {{.BUILD_FLAGS}} -v -coverpkg=./internal/... -coverprofile=coverage.txt ./...
      - go tool cover -html=coverage.txt -o coverage.html
    sources:
      - ./**/*.go
    generates:
      - coverage.txt
      - coverage.html

  test-with-race:
    desc: Run tests
    cmds:
      - go test {{.BUILD_FLAGS}} -race -v -coverpkg=./internal/... -coverprofile=coverage.txt ./...
      - go tool cover -html=coverage.txt -o coverage.html
    sources:
      - ./**/*.go
    generates:
      - coverage.txt
      - coverage.html

  swagger:
    desc: Generate swagger docs
    deps: [go-generate]
    cmds:
      - swag init --quiet --generalInfo v1alpha.go --dir internal/agent/worker/fiber/http/api/v1alpha,internal/utils/http --output internal/agent/worker/fiber/http/api/v1alpha --outputTypes json
      - swag init --quiet --generalInfo v1alpha.go --dir internal/server/worker/fiber/http/api/v1alpha,internal/utils/http --output internal/server/worker/fiber/http/api/v1alpha --outputTypes json
    sources:
      - ./**/*.go
    generates:
      - internal/agent/worker/fiber/http/api/v1alpha/swagger.json
      - internal/server/worker/fiber/http/api/v1alpha/swagger.json
    silent: true

  go-generate:
    desc: Run go generate
    deps: [install-build-deps]
    cmds:
      - go generate ./...
    sources:
      - ./**/*.go
    silent: true

  install-build-deps:
    desc: Install deps to build the project
    cmds:
      - go install github.com/swaggo/swag/cmd/swag@{{.SWAGGO_VERSION}}
      - go install github.com/weastur/replacer/cmd/replacer@{{.REPLACER_VERSION}}
    silent: true

  install-deps:
    desc: Install deps
    deps: [install-build-deps]
    cmds:
      - go install github.com/spf13/cobra-cli@{{.COBRA_CLI_VERSION}}
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin {{.GOLANGCI_LINT_VERSION}}
    silent: true

  clean:
    desc: Clean the project
    cmds:
      - go clean -cache -testcache
      - rm -f maf{{exeExt}}
      - rm -f coverage.txt
      - rm -f coverage.html
      - rm -rf dist/
    silent: true
