---
rules:
  - regex: "(?m)^// @COMMON-HEADERS$"
    repl: |-
      // @Header       all {string} X-Request-ID "UUID of the request"
      // @Header       all {string} X-API-Version "API version, e.g. v1alpha"
      // @Header       all {int} X-Ratelimit-Limit "Rate limit value"
      // @Header       all {int} X-Ratelimit-Remaining "Rate limit remaining"
      // @Header       all {int} X-Ratelimit-Reset "Rate limit reset interval in seconds"
